---
# tasks file for ldap

- name: Set FQDN hostname
  hostname: 
    name: '{{ ipaclient_fqdn }}'

- name: Install ipa packages
  yum: 
   name:
    - ipa-client
   state: latest

- name: Install and configure ipa-client
  command: ipa-client-install --unattended --domain={{ ipadomain }} --server={{ ipaserver_fqdn }} --realm={{ iparealm }} --mkhomedir --hostname={{ ipaclient_fqdn }} --no-ntp --ip-address={{ ipaclient_ip }} --principal admin --password=Otus1234