---
# tasks file for ldap

- name: Set FQDN hostname
  hostname: 
    name: '{{ ipaserver_fqdn }}'

- name: Install ipa-server packages
  yum: 
    name:
    - nss
    - ipa-server
    - ipa-server-dns
    state: latest
    update_cache: yes

#- name: Install and configure IPA server
#  command: ipa-server-install --realm=SERGSHA.LOCAL --domain=sergsha.local --ds-password=Otus1234 --admin-password=Otus1234 --mkhomedir --hostname=ipaserver.sergsha.local --ip-address=192.168.50.10 --no-ntp --unattended --setup-dns --auto-forwarders --auto-reverse

- name: Install and configure ipa-server
  command: ipa-server-install --unattended --ip-address={{ ipaserver_ip }} --hostname={{ ipaserver_fqdn }} --domain={{ ipadomain }} --realm={{ iparealm }} --ds-password=Otus1234 --admin-password=Otus1234 --mkhomedir --setup-dns --forwarder={{ forwarders }} --reverse-zone={{ ipareversezone }} --no-ntp

- name: Get content of ipetrov public key
  debug:
    msg: "{{ lookup('file', 'ipetrov.pub') }}"
    register: ipetrov_pubkey

- name: Create new ipa user
  shell: echo "Otus1234" | ipa user-add ipetrov --first=Ivan --last=Petrov --email=ipetrov@email.ru --shell=/bin/bash --sshpubkey="{{ ipetrov_pubkey.stdout }}" --password

